export const ACTION_TYPE_UPDATE_DATA = 'ACTION_TYPE_UPDATE_DATA';
export const ACTION_TYPE_UPDATE_WALLET = 'ACTION_TYPE_UPDATE_WALLET';
export const ACTION_TYPE_TOGGLE_THEME = 'ACTION_TYPE_TOGGLE_THEME';
export const ACTION_TYPE_IS_MOBILE = 'ACTION_TYPE_IS_MOBILE';
